name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker # this step runs on its own docker file
        uses: docker://node:16-alpine3.11
        with:
          entrypoint: /bin/echo # similar to docker compose file; specifies first command to execute
          args: "Hello World"
      - name: Log node version # this step runs on its own docker file
        uses: docker://node:16-alpine3.11
        with:
          entrypoint: /usr/local/bin/node # similar to docker compose file; specifies first command to execute
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script # this step runs on its own docker file
        uses: docker://node:16-alpine3.11
        with:
          entrypoint: ./script.sh # pass in personal executable file
          args: "Some string"
  node-docker:
    runs-on: ubuntu-latest
    services: # similar to a docker compose file; specify what containers to run and ports
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports: # use mongo instead of localhost for docker-compose
          - "27017:27017"
    container: node:16-alpine3.11
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
