name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10] # make job run for versions 6, 8, and 10
      max-parallel: 3 # limits number of jobs running in parallel in the matrix
      fail-fast: true # if one of the jobs fail, all of the jobs in the matrix will stop
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1 #action that sets up new node version
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log updated node version
        run: node -v
